### ISSUE TITLE
Create repo of static content for GitHub Arctic Code Vault

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#1447]
# HARD DEADLINE 02/02/2020

So, really, before then so we can work out any kinks.

***

GitHub is creating an Archive Program where they archive all public repos in various states of recency and depth.

LOCKSS (lots of copies keep stuff safe)

https://archiveprogram.github.com

This includes printing all of the code on a long term archival film (see above link), in the vein of the [Seed Vault in Svalbard](https://en.wikipedia.org/wiki/Svalbard_Global_Seed_Vault).

***

I want to get all of the content from the site into a series of static files, in a separate repo, before 02/02/2020 so that after the collapse of industrial civilization, when whoever uncovers this thing, they also get an anarchist analysis and narrative of this time that we're in.

***

# Deliverables 

- [x] New repo: https://github.com/crimethinc/website-content
- [ ] Rake task/s to create static file/s and push them into the `crimethinc/website-content` (we can start out running that manually, periodically/daily)
  - [X] `rake static:export` (added https://github.com/crimethinc/website/pull/1475)
  - [ ] `rake static:publish`
- [ ] A ScheduledJob in Heroku land to run these rake tasks every hour or whenever

# Formats

I'm thinking we should export them as HTML and Markdown

- [x] **HTML 5** : Very simple / minimal. No presentational markup. Only semantic content markup.
- [x] **Markdown** : Also very simple / minimal. Maybe some YAML front matter with metadata, like Jekyll does.

# Content

- [x] **Articles** : Number 1 priority is the Articles. Everything past that is bonus.
- [x] **Pages** : /about /library (https://github.com/crimethinc/website/pull/1480 )
- [x] **Tools** : Pages about the tools (poster, zines, stickers, etc). I'm not sure that we should try to put all of the PDFs and images in the repo. Thoughts?
- [X] **Images** : Not sure if we should try to put all of the images from Articles in here too. My hunch is no. Thoughts? (https://github.com/crimethinc/website/pull/1483)

**Comment by just1602** [comment]
Sometime images help to understand content, so maybe extracting images could be a good idea, no?

**Comment by veganstraightedge** [comment]
@just1602 Agreed.

If we can get the articles in place in time too, that'd be great.

**Comment by astronaut-wannabe** [comment]
# structure of the archive repo
so, I am thinking of a structure like 
```sh
~/cwc/website-content$ tree .
.
├── html
│   ├── articles
│   ├── tools
│   └── zines
├── LICENSE
├── markdown
│   ├── articles
│   ├── tools
│   └── zines
└── README.md
```

And then the directories (e.g. `/markdown/articles`) would be flat directories of files

# sketch of an archiver
something like this
```ruby
# TODO: How do you use this thing

class CodeArchiver
  class << self
    def put_it_on_ice
      article = Article.first
      File.open("#{filename_from(article)}.md", 'w') do |file|
        file.puts "# #{article.title}"
        file.puts "## #{article.subtitle}" unless article.subtitle.blank?
        file.puts to_markdown article
      end

      File.open("#{filename_from(article)}.html", 'w') do |file|
        file.puts "<h1>#{article.title}</h1>"
        file.puts "<h2>#{article.subtitle}</h2>" unless article.subtitle.blank?
        file.puts to_html article
      end
    end

    private

    def filename_from article
      article.path.tr('/', '_')
    end

    def to_html article
      Kramdown::Document.new(
        MarkdownMedia.parse(article.content, include_media: false),
        input:                     :kramdown,
        remove_block_html_tags:    false,
        transliterated_header_ids: true
      ).to_html
    end

    def to_markdown article
      Kramdown::Document.new(
        MarkdownMedia.parse(article.content, include_media: false),
        input:                     :kramdown,
        remove_block_html_tags:    false,
        transliterated_header_ids: true
      ).to_kramdown
    end
  end
end
```

could be run in a job and would create two files per article like this:
- [_2019_12_25_merry-crisis-and-a-happy-new-fear-repression-and-resistance-in-greece-december-2019.html](https://github.com/crimethinc/website/files/4029151/_2019_12_25_merry-crisis-and-a-happy-new-fear-repression-and-resistance-in-greece-december-2019.html.txt)
- [_2019_12_25_merry-crisis-and-a-happy-new-fear-repression-and-resistance-in-greece-december-2019.md](https://github.com/crimethinc/website/files/4029152/_2019_12_25_merry-crisis-and-a-happy-new-fear-repression-and-resistance-in-greece-december-2019.md.txt)


-

**Comment by veganstraightedge** [comment]
Great start, @astronaut-wannabe! 🎉

**Comment by veganstraightedge** [comment]
Now that we've got some of this in place and I'm starting to think more about images being in the mix, I think the folder/file structures should be different.

Instead of separating the markdown/html files, I think they should be intermixed. Like this:

```
.
├── articles
│   ├── 1996
│   │   └── 01
│   │       └── 01
│   │           ├── how-ethical-is-the-work-ethic.html
│   │           ├── how-ethical-is-the-work-ethic.md
│   │           ├── how-i-spent-my-permanent-vacation.html
│   │           ├── how-i-spent-my-permanent-vacation.md
│   │           ├── introduction-to-the-situationists.html
│   │           ├── introduction-to-the-situationists.md
│   │           └── selling-ourselves-out.html
│   │           └── selling-ourselves-out.md

└── pages
    ├── about.html
    ├── about.md
    └── faq.html
    └── faq.md
```

This would allow us to put the images (etc) in the same article day folder (for example) and use them easily by both `md` and `html` files.

What do you think?

**Comment by veganstraightedge** [comment]
Related, what do you think the effort is to leave the `[[ ]]` or `<img>` tags in places in `md` and `html` files?

As an initial move, I'm willing to manually move the images from S3 to the `website-content` repo. And manually update the URLs to images, if need.

**Comment by veganstraightedge** [comment]
This is great work so far! 🎉

***

One new little thing that presented itself when image tags were added: leading blankspace is significant.

<img width="931" alt="Screen Shot 2020-01-28 at 9 31 37 AM" src="https://user-images.githubusercontent.com/4361/73289234-3c9a8d80-41b1-11ea-86a1-0c7a3cc87afe.png">

***

Can you clean up the HTML generated from MarkdownMedia in these ways:

- [ ] Strip all leading blankspace
- [ ] Strip all blank lines between HTML tags

```diff
-<figure class="">
-
-      <img src="https://cloudfront.crimethinc.com/assets/articles/1999/07/30/atom-and-his-package.jpg" />
-
-
-    <figcaption><p>From <a href="atomandhispackage.com">http://atomandhispackage.com/news.html</a></p>
-</figcaption>
-  </figure>
```

```diff
+<figure class="">
+<img src="https://cloudfront.crimethinc.com/assets/articles/1999/07/30/atom-and-his-package.jpg" />
+<figcaption><p>From <a href="atomandhispackage.com">http://atomandhispackage.com/news.html</a></p>
+</figcaption>
+</figure>
```

**Comment by astronaut-wannabe** [comment]
the deadline has passed, closing the issue
