### ISSUE TITLE
Bug bash call for help!

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#400]
@guitsaru @greggawatt @gesa @just1602 @withoutboats @astronaut-wannabe @eliduke
@evanphx @mutantmonkey @carols10cents @steveklabnik @benatcwc

Hi all. You're mentioned here because you've helped out in someway big or small on this codebase. We all appreciate dearly your contributions. As summer winds down, we have plans for a few medium/biggerish projects. But I'd really like to clean house a little bit before getting into those things. If you could find the time and motivation to chip away at a couple few of these issues, it'd really help us get to our _Next Big Things™_.

If you can do any of these, that'd mean the world to me. <3

# Rails / Backend

- [ ] #351: Design better default button style
- [ ] #415 : Add draft preview mode to podcast episodes 
- [ ] #416: Add published_at / draft mode to Tools
- [ ] #417: Add draft preview mode to tools 
- [ ] #101: Build / design real settings section
- [x] #282: Generate Redirect from Article.short_path
- [x] #374: BUG: Feed niling
- [x] #381: Redirect nested article to parent article
- [x] #410: Update slug generation behavior 
- [x] #339: Add draft/publilshed to Podcast Episodes
- [x] #340: Don't try to create a Redirect when short_path is empty

# Content 

- [ ] #147: Add all /category/features to a real category
- [ ] #192: Collect all blog post comments from old site
- [ ] #373: Fix missing images on /rt
- [x] #185: Footnotes attached to the wrong text?

# Rails / Frontend

- [ ] #390: Add tags to books/zines and posters/stickers
- [ ] #391: Add publication status to books/zines and posters/stickers and (podcast) episodes
- [x] #396: Fix [[]]
- [x] #354: Add media embed support for Instagram
- [x] #386: Add /edit to more resources
- [x] #144: Add Danger Zone to all admin CRUD edit views
- [x] #409: Add explanatory note to slug field in Article form 
- [x] #408: Add UTC time note to Article form
- [x] #350: Change CMS note on Article Specific CSS field
- [x] #397: Fix specs
- [x] #399: Search error : with quote in query

# Design / Frontend

- [ ] #360: Make article header text smaller on mobile
- [ ] #80: Build Share sheet
- [ ] #157: Make custom 404, 500 and 422 pages
- [ ] #190: Refine design of /books/work/extra
- [ ] #195: Create custom branded Heroku error pages
- [ ] #392: Use article.content_rendered instead of render_content() ?
- [x] #394: Add 'Subscribe' to header nav

# Performance

- [ ] #196: Turn on heavy caching
- [ ] #103: Tune pg performance
- [ ] #254: Turn on GZIP for homepage and favicon.ico
- [x] #255: Turn on browser caching for static assets
- [ ] #287: Explore setting Expiry headers setting well

# Infrastructure

- [ ] #223: Put staging.crimethinc.com behind HTTP Basic Auth
- [ ] #226: Setup Staging ENV on staging server
- [ ] #262: Create nightly job to site back up to HTML on S3
- [ ] #383: Fix seeds script
- [ ] #55: Add CONTRIBUTING.md

**Comment by greggawatt** [comment]
This sounds like a substantial list, I'd love to help out. Is there any sort of priority queue you want to assign to these items?

**Comment by kmanzana** [comment]
My thoughts as well.  Might I suggest using Waffle.io to prioritize the issues and allow people to see status of different issues?

**Comment by veganstraightedge** [comment]
There is no priority to this list. They're all nice to haves. 

If anything strikes your fancy and you want to do it, great! Don't worry about where it is in the list. If you want to claim an issue to avoid duplicate effort, just leave a comment on that issue saying you're working on it.

Re: waffle.io: I don't want to add another level of organization and another tool to have to use. If we do really really need prioritization, we can use a Milestone in here. But for now, let's keep it lean. :D

**Comment by veganstraightedge** [comment]
Updated the issue into sections of tasks to make finding works that matches interests easier. Hope it helps.

**Comment by veganstraightedge** [comment]
@greggawatt @kmanzana Does the re-org into lists help you make sense of what there is to do that might match your interest and ability? Lemme know if there's anything I can do to help you get ramped up. 👍🏻

**Comment by greggawatt** [comment]
@veganstraightedge this helps, thanks! I'll pick something off the stack this week
