### ISSUE TITLE
Books in Lite Mode

### ISSUE THREAD

**Issue by veganstraightedge** [crimethinc/website#961]
Don't render images when in Lite Mode.

## Examples:
https://crimethinc.com/books
https://crimethinc.com/books/no-wall-they-can-build
https://crimethinc.com/books/lit-kit

## TODO

- [ ] /books 
  - [ ] hero image (book spines)
  - [ ] book cover images
- [ ] /books/lit-kit 
  - [ ] sidebar images 
- [ ] /books/:slug
  - [ ] cover images 
  - [ ] gallery images
